site_name: Wox Wiki
docs_dir: 'docs'
markdown_extensions: []
repo_url: 'https://github.com/HsunGong/Wox.Wiki'

theme: 
  name: material
  favicon: 'imgs/app.jpg'

markdown_extensions:
  - footnotes
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: ['en']

nav:
- Home: index.md

- Basic Usage:
  - Install Wox: install.md
  - Getting started: usage.md
  - Built-In Plugins: plugins.md
  - Themes: themes.md
  - Settings: settings.md

# - Plugins:
#   - Built-In plugins: plugins.md
#   - Install a plugin: plugins/install.md
#   - Explore a plugin: plugins/explore.md
#   - Develop a plugin: plugins/develop.md

- Develop:
  - Develop a theme: themes.md
  - Develop a plugin: plugins/develop.md
  - Develop Wox: develop.md

- Reference:
  - Repo in Github: refer/source.md
  - mkdocs: refer/mkdocs.md
  - Python markdown: refer/pymdown.md
