site_name: Wox Wiki

nav:
- Home: readme.md

- Basic Usage:
  - Install Wox: basic/install.md
  - Getting started: basic/usage.md
  - Built-In Plugins: basic/plugins.md
  - Themes: basic/themes.md
  - Settings: basic/settings.md

- Plugins:
  - Built-In plugins: basic/plugins.md
  - Install a plugin: plugins/install.md
  - Explore a plugin: plugins/explore.md
  - Develop a plugin: plugins/develop.md

- Develop:
  - Develop a theme: basic/themes.md
  - Develop a plugin: plugins/develop.md
  - Develop Wox: basic/develop.md

- Reference:
  - Repo in Github: refer/source.md
  - mkdocs: refer/mkdocs.md

theme: readthedocs
