site_name: Wox Wiki
docs_dir: 'docs'
markdown_extensions: []
repo_url: 'https://github.com/HsunGong/Wox.Wiki'
site_favicon: 'imgs/app.jpg'

theme: material

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: ['en']

nav:
- Home: index.md

- Basic Usage:
  - Install Wox: basic/install.md
  - Getting started: basic/usage.md
  - Built-In Plugins: basic/plugins.md
  - Themes: basic/themes.md
  - Settings: basic/settings.md

- Plugins:
  - Built-In plugins: basic/plugins.md
  - Install a plugin: plugins/install.md
  - Explore a plugin: plugins/explore.md
  - Develop a plugin: plugins/develop.md

- Develop:
  - Develop a theme: basic/themes.md
  - Develop a plugin: plugins/develop.md
  - Develop Wox: basic/develop.md

- Reference:
  - Repo in Github: refer/source.md
  - mkdocs: refer/mkdocs.md
