site_name: 'Wox Wiki: Documentation for Wox Launcher'
docs_dir: docs
copyright: Copyright &copy; 2019 - Now Xun Gong

nav:
- Home: index.md

- Basic Usage:
  - Install Wox: install.md
  - Getting started: usage.md
  - Built-In Plugins: plugins.md
  - Themes: themes.md
  - Settings: settings.md

# - Plugins:
#   - Built-In plugins: plugins.md
#   - Install a plugin: plugins/install.md
#   - Explore a plugin: plugins/explore.md
#   - Develop a plugin: plugins/develop.md

- Develop:
  - Develop a theme: themes.md
  - Develop a plugin: plugins/develop.md
  - Develop Wox: develop.md

- Reference:
  - Repo in Github: refer/source.md
  - mkdocs: refer/mkdocs.md
  - Python markdown: refer/pymdown.md

theme: 
  name: material
  favicon: imgs/app.jpg

markdown_extensions:
  - footnotes
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - localsearch
# Lang: jp support zh-CN?

repo_url: https://github.com/HsunGong/Wox.Wiki
extra:
# manifest: 'manifest.webmanifest'
  social:
    - type: github
      link: https://github.com/HsunGong
